<?php

namespace Miky\Bundle\MediaBundle\Repository;

/**
 * GalleryHasMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryHasMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
