miky_media:
    default_context: default
    contexts:
        default:  # the default context is mandatory
            providers:
                - miky.media.provider.dailymotion
                - miky.media.provider.youtube
                - miky.media.provider.image
                - miky.media.provider.file
            formats:
                icon: {width: 50, quality: 100}
                small: { width: 100 , quality: 100}
                medium: { width: 250 , quality: 100}
                big:   { width: 500 , quality: 100}